import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import { Header } from "@/components/header";
import { UserContextProvider } from "@/contexts/UserContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Amigo oculto",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <UserContextProvider>
          <div className="sm:hidden">
            <Header />
            {children}
          </div>

          <div className="text-center hidden w-full h-screen sm:flex items-center justify-center">
            <h2>
              Sentimos muito!
              <br />
              Este site só está disponível em dispositivos móveis no momento.
              <br />
              Tente acessar em um smartphone.
            </h2>
          </div>
        </UserContextProvider>
      </body>
    </html>
  );
}
